[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
via_ir = true
evm_version = 'paris'
verbosity = 2
cache = true

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[rpc_endpoints]
fantom = "${RPC_URL}"